### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lowping23** [AICoin-io/AICoin#1]
Getting error "This account holds no coins or has already voted its full balance on the ballot".
Coins are on the address. Have been there for 40 hours. Haven't made a successful vote yet.
Let me know if you need more info

**Comment by BitcoinDBA** [comment]
Hi higzac,

Could you send me the public address where the AICoins are held, so I can replicate the issue?
My own address seems to reflect its status correctly. If you'd rather not post here you can email it directly to support AT firstglobalcredit.com.

Thanks,
BitcoinDBA

**Comment by lowping23** [comment]
Hi BitcoinDBA
0xd6484c54e20B7095a9d17266B608e714a57fc2E9

I ran the test today using Chrome and the test vote completed without issue.

I was trying to Vote yesterday using the Brave browser.
The coins show up in the AICoin wallet using brave. The error happens when you try to vote.

One other thing that might be of interest.
I had another empty ETH address added to the AICoin wallet.
So x2 ETH addresses listed in wallet.
One had XAI the other didn't.
When making the vote I made sure to select the ETH address with the XAI on it.

**Comment by BitcoinDBA** [comment]
Hi higzac,

The Brave browser is not one that we have tested with. I am glad that the vote worked using  Chrome, however.

Thanks,
BitcoinDBA

**Comment by lowping23** [comment]
No worries.
Happy to use chrome when the vote happens.
Possibly list the supported browsers when the official email for the new vote date goes out.

All the best.
higzac

**Comment by BitcoinDBA** [comment]
Hi higzac,

Yes, that is an important point, thanks for reminding us that people use many different browsers.

Many thanks,
BitcoinDBA
